/**
 * Generate LIFECYCLES.md — the lifecycle reference doc.
 *
 * Reads UPG_LIFECYCLES + UPG_LIFECYCLE_FREE_TYPES + UPG_LIFECYCLE_PLANNED_TYPES
 * and renders a markdown reference for every lifecycle, template, lifecycle-free
 * type, and planned type. Run on schema changes; the doc never drifts.
 *
 * Usage: npx tsx scripts/generate-lifecycles-doc.ts
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import {
  UPG_LIFECYCLES,
  UPG_LIFECYCLE_FREE_TYPES,
  UPG_LIFECYCLE_PLANNED_TYPES,
  type UPGLifecycle,
  type LifecyclePhase,
} from '../src/grammar/lifecycles.js'
import { UPG_ENTITY_TO_DOMAIN } from '../src/registry/domains.js'

const OUT_PATH = path.join(import.meta.dirname, '..', 'src', 'grammar', 'LIFECYCLES.md')

// ─── Helpers ────────────────────────────────────────────────────────────────

function phaseChain(lifecycle: UPGLifecycle): string {
  return lifecycle.phases.map((p) => p.id).join(' → ')
}

function terminals(lifecycle: UPGLifecycle): string {
  return lifecycle.terminal_phases.length > 0
    ? lifecycle.terminal_phases.map((p) => `\`${p}\``).join(', ')
    : '_(none)_'
}

function hasReopen(lifecycle: UPGLifecycle): boolean {
  const terminalSet = new Set(lifecycle.terminal_phases)
  return lifecycle.phases.some(
    (p) => terminalSet.has(p.id) && p.transitions_to.length > 0,
  )
}

function domainOf(entityType: string): string {
  return (UPG_ENTITY_TO_DOMAIN as Record<string, string>)[entityType] ?? '_(unmapped)_'
}

function row(cells: string[]): string {
  return `| ${cells.join(' | ')} |`
}

// ─── Sections ───────────────────────────────────────────────────────────────

function renderHandAuthoredTable(): string {
  const handAuthored = UPG_LIFECYCLES.filter((l) => !l.template_id)
  const sorted = [...handAuthored].sort((a, b) => {
    const da = domainOf(a.entity_type)
    const db = domainOf(b.entity_type)
    if (da !== db) return da.localeCompare(db)
    return a.entity_type.localeCompare(b.entity_type)
  })

  const lines: string[] = []
  lines.push(`## Hand-authored lifecycles (${handAuthored.length})`)
  lines.push('')
  lines.push(
    'Lifecycles defined directly in `lifecycles.ts` because the entity carries a state machine that doesn\'t fit one of the reusable templates.',
  )
  lines.push('')
  lines.push(row(['Type', 'Domain', 'Initial', 'Phases', 'Terminals', 'Reopen?']))
  lines.push(row(['---', '---', '---', '---', '---', '---']))
  for (const l of sorted) {
    lines.push(
      row([
        `\`${l.entity_type}\``,
        domainOf(l.entity_type),
        `\`${l.initial_phase}\``,
        phaseChain(l),
        terminals(l),
        hasReopen(l) ? 'yes' : 'no',
      ]),
    )
  }
  return lines.join('\n')
}

function renderTemplateDerivedTable(): string {
  const templated = UPG_LIFECYCLES.filter((l) => l.template_id)
  const sorted = [...templated].sort((a, b) => {
    const ta = a.template_id ?? ''
    const tb = b.template_id ?? ''
    if (ta !== tb) return ta.localeCompare(tb)
    return a.entity_type.localeCompare(b.entity_type)
  })

  const lines: string[] = []
  lines.push(`## Template-derived lifecycles (${templated.length})`)
  lines.push('')
  lines.push(
    'Lifecycles generated by `fromTemplate()` from one of the reusable templates. Adding a new entity type to an existing template is a one-line change in `TEMPLATE_LIFECYCLES`.',
  )
  lines.push('')
  lines.push(row(['Type', 'Domain', 'Template', 'Initial', 'Terminals']))
  lines.push(row(['---', '---', '---', '---', '---']))
  for (const l of sorted) {
    lines.push(
      row([
        `\`${l.entity_type}\``,
        domainOf(l.entity_type),
        `\`${l.template_id}\``,
        `\`${l.initial_phase}\``,
        terminals(l),
      ]),
    )
  }
  return lines.join('\n')
}

function renderTemplatesSection(): string {
  // Dedupe templates by template_id from UPG_LIFECYCLES (one example each).
  const seen = new Map<string, UPGLifecycle>()
  for (const l of UPG_LIFECYCLES) {
    if (l.template_id && !seen.has(l.template_id)) {
      seen.set(l.template_id, l)
    }
  }
  const templateIds = [...seen.keys()].sort()

  const lines: string[] = []
  lines.push(`## Templates (${templateIds.length})`)
  lines.push('')
  lines.push(
    'Reusable lifecycle patterns. Each entity type registered against a template inherits the template\'s phases verbatim. Add a type to a template via `TEMPLATE_LIFECYCLES` in `lifecycles.ts`.',
  )
  lines.push('')
  for (const id of templateIds) {
    const example = seen.get(id)!
    const consumers = UPG_LIFECYCLES.filter((l) => l.template_id === id).map(
      (l) => l.entity_type,
    )
    lines.push(`### \`${id}\` (${consumers.length} consumer${consumers.length === 1 ? '' : 's'})`)
    lines.push('')
    lines.push(`**Initial:** \`${example.initial_phase}\` · **Terminals:** ${terminals(example)} · **Reopen:** ${hasReopen(example) ? 'yes' : 'no'}`)
    lines.push('')
    lines.push('Phases:')
    lines.push('')
    for (const p of example.phases) {
      const isTerminal = example.terminal_phases.includes(p.id)
      const targets = p.transitions_to.length > 0 ? p.transitions_to.map((t) => `\`${t}\``).join(', ') : '_(end)_'
      lines.push(`- \`${p.id}\`${isTerminal ? ' [terminal]' : ''} — ${p.label}. → ${targets}`)
    }
    lines.push('')
    lines.push('Applied to:')
    lines.push('')
    lines.push(consumers.map((c) => `\`${c}\``).join(', '))
    lines.push('')
  }
  return lines.join('\n')
}

function renderLifecycleFreeSection(): string {
  const free = [...UPG_LIFECYCLE_FREE_TYPES].sort((a, b) => {
    const da = domainOf(a)
    const db = domainOf(b)
    if (da !== db) return da.localeCompare(db)
    return a.localeCompare(b)
  })

  const grouped = new Map<string, string[]>()
  for (const t of free) {
    const d = domainOf(t)
    if (!grouped.has(d)) grouped.set(d, [])
    grouped.get(d)!.push(t)
  }

  const lines: string[] = []
  lines.push(`## Lifecycle-free types (${free.length})`)
  lines.push('')
  lines.push(
    'Types that deliberately do not carry a status lifecycle. Reference data (vocabularies, lookups), structural primitives (atoms of a composite), immutable data points, configuration, append-only ledger entries, computed values, and DDD modelling primitives. Source of truth: `UPG_LIFECYCLE_FREE_TYPES` in `lifecycles.ts`.',
  )
  lines.push('')
  const domains = [...grouped.keys()].sort()
  for (const d of domains) {
    const types = grouped.get(d)!
    lines.push(`### ${d} (${types.length})`)
    lines.push('')
    lines.push(types.map((t) => `\`${t}\``).join(', '))
    lines.push('')
  }
  return lines.join('\n')
}

function renderPlannedSection(): string {
  const planned = [...UPG_LIFECYCLE_PLANNED_TYPES].sort((a, b) => {
    const da = domainOf(a)
    const db = domainOf(b)
    if (da !== db) return da.localeCompare(db)
    return a.localeCompare(b)
  })

  const lines: string[] = []
  lines.push(`## Planned types (${planned.length})`)
  lines.push('')
  lines.push(
    'Types triaged for a future lifecycle but not yet implemented. As lifecycles land, types migrate from this set into `UPG_LIFECYCLES`. Source of truth: `UPG_LIFECYCLE_PLANNED_TYPES` in `lifecycles.ts`.',
  )
  lines.push('')
  lines.push(planned.map((t) => `\`${t}\``).join(', '))
  return lines.join('\n')
}

// ─── Header / preamble ──────────────────────────────────────────────────────

function renderPreamble(handCount: number, templateCount: number, freeCount: number, plannedCount: number): string {
  const totalImplemented = handCount + templateCount
  return `<!-- AUTO-GENERATED by scripts/generate-lifecycles-doc.ts. Do not edit manually. Re-run after lifecycle changes. -->

# UPG Lifecycles Reference

Every entity type's status journey, in one table. **${totalImplemented} types carry a lifecycle today** (${handCount} hand-authored + ${templateCount} template-derived). **${freeCount} types are deliberately lifecycle-free**, and **${plannedCount} are triaged for a future lifecycle**.

## Model

UPG lifecycles are **two-level**:

- **Phases** are the universal vocabulary every consumer can rely on (e.g. \`draft\`, \`review\`, \`published\`). Phases are fixed by the spec for each lifecycle and surface on the entity's \`status\` property.
- **States** (optional, finer-grained) are sub-positions within a phase, defined inline on \`LifecyclePhase.core_states\`. Tools may extend states locally via \`lifecycle_extensions\` on the document.

\`UPGLifecycle.terminal_phases\` lists the phases that represent **completion**. Terminal phases may still declare \`transitions_to\` — these are **late-state moves** (reopen, revive, deprecate after approval) and are NOT forward progression. Consumers treating "terminal = done" should respect this distinction.

**Templates** are reusable phase chains shared across many entity types. Six templates today: \`PUBLISHING\`, \`OPERATIONAL\`, \`APPROVAL\`, \`WORK_ITEM\`, \`DISCOVERY\`, \`MATURITY\`. A type generated from a template carries the template's id on \`UPGLifecycle.template_id\` so render and audit tooling can group, label, and link templates without re-detecting them structurally.

\`getLifecycleRenderShape(entityType)\` returns a flattened, render-ready shape for any type — phase-level only, with transitions classified as \`forward | backward | terminal | reopen\`.

---

`
}

// ─── Main ───────────────────────────────────────────────────────────────────

function main(): void {
  const handCount = UPG_LIFECYCLES.filter((l) => !l.template_id).length
  const templateCount = UPG_LIFECYCLES.filter((l) => l.template_id).length
  const freeCount = UPG_LIFECYCLE_FREE_TYPES.size
  const plannedCount = UPG_LIFECYCLE_PLANNED_TYPES.size

  const sections = [
    renderPreamble(handCount, templateCount, freeCount, plannedCount),
    renderHandAuthoredTable(),
    '',
    '---',
    '',
    renderTemplateDerivedTable(),
    '',
    '---',
    '',
    renderTemplatesSection(),
    '---',
    '',
    renderLifecycleFreeSection(),
    '---',
    '',
    renderPlannedSection(),
    '',
  ]

  fs.writeFileSync(OUT_PATH, sections.join('\n'))
  console.log(
    `Wrote ${OUT_PATH}\n  ${handCount} hand-authored · ${templateCount} template-derived · ${freeCount} lifecycle-free · ${plannedCount} planned`,
  )
}

// Quiet the unused-import warning for LifecyclePhase by exposing it as a type-only re-export hint.
type _UnusedPhaseHint = LifecyclePhase

main()
